### ISSUE TITLE
prism-break.org https certificate is broken

### ISSUE THREAD

**Issue by mcastillof** [prism-break/prism-break#2040]
https://www.prism-break.org/

Websites prove their identity via certificates. Firefox does not trust this site because 
it uses a certificate that is not valid for prism-break.org. The certificate is only valid 
for the following names: ***.gitlab.io, gitlab.io**
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by yegortimoshenko** [comment]
See: https://status.gitlab.com/pages/incident/5b36dc6502d06804c08349f7/5f04887c3cb21204bf8b5d1e
